class ActionTypes:
	UPDATE_MESSAGES = "UPDATE_MESSAGES"
	DELETE_MESSAGE = "DELETE_MESSAGE"
	SEND_MESSAGE = "SEND_MESSAGE"
	UPDATE_GHOSTS = "UPDATE_GHOSTS"
	DISCONNECT = "DISCONNECT"
	CONNECT_TO_BIAS = "CONNECT_TO_BIAS"
	DELETE_BIAS = "DELETE_BIAS"
	CREATE_BIAS = "CREATE_BIAS"
	GET_BIAS = "GET_BIAS"
	GET_BIASES = "GET_BIASES"

class InvisibleTypes:
	WHO_IS_THERE = "WHO_IS_THERE"
	I_AM_HERE = "I_AM_HERE"
	I_WENT_OUT = "I_WENT_OUT"
	I_JOINED = "I_JOINED"

class LogTypes:
	FORGOTTEN_BIASES = "log/forgotten.json"

class ExceptionTypes:
	NO_INTERNET_CONNECTION = "NO_INTERNET_CONNECTION"
	BIAS_HAS_BEEN_DESTROYED = "BIAS_HAS_BEEN_DESTROYED"
	WRONG_BIAS_KEY = "WRONG_BIAS_KEY"
	YOU_WHERE_KICKED = "YOU_WHERE_KICKED"